#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
dbus-launch /usr/bin/startxfce4 &
# startxfce4 &

autocutsel -f

export LANG=zh_CN.UTF-8 # 启用中文环境
# scim –d  # 加载scim中文输入法
# XMODIFIERS="@im=SCIM"
# export XMODIFIERS
# export GTK_IM_MODULE=scim



#!/bin/bash
export XMODIFIERS=@im=SCIM
export GTK_IM_MODULE="xim"
# export QT_IM_MODULE="scim"

# for xfce
export QT_IM_MODULE="scim-bridge"
scim -d

# startlxde &
# /usr/bin/ibus-daemon -d &

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
vncconfig -iconic &


# 开终端
# x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &

# x-window-manager &

# gnome-panel &
# gnome-settings-daemon &
# metacity &
# nautilus &

